version: "3"

services:
  garage:
    container_name: garage
    image: dxflrs/garage:v0.9.0
    network_mode: "host"
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage-meta:/var/lib/garage/meta:rw
      - garage-data:/var/lib/garage/data:rw

  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    restart: always

volumes:
  # Object storage
  garage-data:
  garage-meta:
